name: Terraform Azure Monitoring Workflow

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Terraform CI
    runs-on: ubuntu-latest

    steps:

      # Checkout Repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Install Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # Verify Terraform Version
      - name: Terraform Version
        run: terraform version

      # Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # Format Check
      - name: Terraform Format
        run: terraform fmt -check

      # Validate Terraform Files
      - name: Terraform Validate
        run: terraform validate

      # Terraform Plan
      - name: Terraform Plan
        run: terraform plan